volumes:
  datafiles:

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Firelegend101
      MYSQL_DATABASE: blog
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pFirelegend101"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
    restart: always
    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      
      
    volumes:
      - ~/.aspnet/https:/https:ro

