version: "3.4"

volumes:
  datafiles:

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Firelegend101
      MYSQL_DATABASE: blog

  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
      - "443:443"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Firelegend101
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      
    volumes:
      - ~/.aspnet/https:/https:ro


