version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      certbot:
        condition: service_completed_successfully
    entrypoint: /bin/sh -c "while [ ! -f /etc/letsencrypt/live/micahshouse.me/fullchain.pem ]; do sleep 1; done && nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: >
      sh -c "mkdir -p /var/www/certbot &&
             certbot certonly --webroot -w /var/www/certbot
             --email xicer029@gmail.com --agree-tos --no-eff-email
             -d micahshouse.me -d www.micahshouse.me -d blog.micahshouse.me &&
             touch /etc/letsencrypt/.certs_created"

  mvc:
    image: blog-mvc-1
    container_name: mvc
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  certbot_conf:
  certbot_www: